import { db } from '@/db';
import { flights } from '@/db/schema';

async function main() {
    const sampleFlights = [
        // Domestic Flights - Mumbai to Delhi
        {
            airline: 'Air India',
            flightNumber: 'AI-101',
            fromLocation: 'Mumbai',
            toLocation: 'Delhi',
            departure: '06:00 AM',
            arrival: '08:15 AM',
            duration: '2h 15m',
            stops: 'Non-stop',
            price: 5200,
            class: 'Economy',
            date: '2024-02-15',
            availableSeats: 120,
            createdAt: new Date().toISOString(),
        },
        {
            airline: 'IndiGo',
            flightNumber: '6E-234',
            fromLocation: 'Mumbai',
            toLocation: 'Delhi',
            departure: '02:30 PM',
            arrival: '04:45 PM',
            duration: '2h 15m',
            stops: 'Non-stop',
            price: 4800,
            class: 'Economy',
            date: '2024-02-15',
            availableSeats: 150,
            createdAt: new Date().toISOString(),
        },
        {
            airline: 'Vistara',
            flightNumber: 'UK-890',
            fromLocation: 'Mumbai',
            toLocation: 'Delhi',
            departure: '09:00 AM',
            arrival: '11:20 AM',
            duration: '2h 20m',
            stops: 'Non-stop',
            price: 15500,
            class: 'Business',
            date: '2024-02-20',
            availableSeats: 80,
            createdAt: new Date().toISOString(),
        },
        // Bangalore to Hyderabad
        {
            airline: 'SpiceJet',
            flightNumber: 'SG-567',
            fromLocation: 'Bangalore',
            toLocation: 'Hyderabad',
            departure: '07:30 AM',
            arrival: '08:45 AM',
            duration: '1h 15m',
            stops: 'Non-stop',
            price: 3200,
            class: 'Economy',
            date: '2024-02-18',
            availableSeats: 140,
            createdAt: new Date().toISOString(),
        },
        {
            airline: 'IndiGo',
            flightNumber: '6E-789',
            fromLocation: 'Bangalore',
            toLocation: 'Hyderabad',
            departure: '05:15 PM',
            arrival: '06:35 PM',
            duration: '1h 20m',
            stops: 'Non-stop',
            price: 3500,
            class: 'Economy',
            date: '2024-02-25',
            availableSeats: 160,
            createdAt: new Date().toISOString(),
        },
        // Delhi to Goa
        {
            airline: 'Air India',
            flightNumber: 'AI-456',
            fromLocation: 'Delhi',
            toLocation: 'Goa',
            departure: '10:30 AM',
            arrival: '01:15 PM',
            duration: '2h 45m',
            stops: 'Non-stop',
            price: 6800,
            class: 'Economy',
            date: '2024-03-01',
            availableSeats: 100,
            createdAt: new Date().toISOString(),
        },
        {
            airline: 'Vistara',
            flightNumber: 'UK-345',
            fromLocation: 'Delhi',
            toLocation: 'Goa',
            departure: '03:45 PM',
            arrival: '06:30 PM',
            duration: '2h 45m',
            stops: 'Non-stop',
            price: 18000,
            class: 'Business',
            date: '2024-03-05',
            availableSeats: 70,
            createdAt: new Date().toISOString(),
        },
        // Chennai to Kolkata
        {
            airline: 'IndiGo',
            flightNumber: '6E-901',
            fromLocation: 'Chennai',
            toLocation: 'Kolkata',
            departure: '08:00 AM',
            arrival: '10:45 AM',
            duration: '2h 45m',
            stops: 'Non-stop',
            price: 5500,
            class: 'Economy',
            date: '2024-02-22',
            availableSeats: 130,
            createdAt: new Date().toISOString(),
        },
        {
            airline: 'SpiceJet',
            flightNumber: 'SG-123',
            fromLocation: 'Chennai',
            toLocation: 'Kolkata',
            departure: '06:30 PM',
            arrival: '09:10 PM',
            duration: '2h 40m',
            stops: '1 Stop',
            price: 4200,
            class: 'Economy',
            date: '2024-02-28',
            availableSeats: 110,
            createdAt: new Date().toISOString(),
        },
        // Pune to Ahmedabad
        {
            airline: 'IndiGo',
            flightNumber: '6E-445',
            fromLocation: 'Pune',
            toLocation: 'Ahmedabad',
            departure: '11:00 AM',
            arrival: '12:30 PM',
            duration: '1h 30m',
            stops: 'Non-stop',
            price: 3800,
            class: 'Economy',
            date: '2024-03-10',
            availableSeats: 145,
            createdAt: new Date().toISOString(),
        },
        // International Flights - Delhi to Dubai
        {
            airline: 'Emirates',
            flightNumber: 'EK-432',
            fromLocation: 'Delhi',
            toLocation: 'Dubai',
            departure: '03:00 AM',
            arrival: '05:30 AM',
            duration: '3h 30m',
            stops: 'Non-stop',
            price: 35000,
            class: 'Economy',
            date: '2024-02-16',
            availableSeats: 180,
            createdAt: new Date().toISOString(),
        },
        {
            airline: 'Emirates',
            flightNumber: 'EK-501',
            fromLocation: 'Delhi',
            toLocation: 'Dubai',
            departure: '10:30 PM',
            arrival: '01:00 AM',
            duration: '3h 30m',
            stops: 'Non-stop',
            price: 120000,
            class: 'Business',
            date: '2024-02-20',
            availableSeats: 60,
            createdAt: new Date().toISOString(),
        },
        {
            airline: 'Emirates',
            flightNumber: 'EK-789',
            fromLocation: 'Mumbai',
            toLocation: 'Dubai',
            departure: '08:45 AM',
            arrival: '10:45 AM',
            duration: '3h 00m',
            stops: 'Non-stop',
            price: 280000,
            class: 'First Class',
            date: '2024-03-08',
            availableSeats: 50,
            createdAt: new Date().toISOString(),
        },
        // Mumbai to Singapore
        {
            airline: 'Singapore Airlines',
            flightNumber: 'SQ-423',
            fromLocation: 'Mumbai',
            toLocation: 'Singapore',
            departure: '11:45 PM',
            arrival: '07:15 AM',
            duration: '5h 30m',
            stops: 'Non-stop',
            price: 42000,
            class: 'Economy',
            date: '2024-02-19',
            availableSeats: 170,
            createdAt: new Date().toISOString(),
        },
        {
            airline: 'Singapore Airlines',
            flightNumber: 'SQ-678',
            fromLocation: 'Delhi',
            toLocation: 'Singapore',
            departure: '01:30 AM',
            arrival: '09:45 AM',
            duration: '6h 15m',
            stops: 'Non-stop',
            price: 95000,
            class: 'Business',
            date: '2024-03-02',
            availableSeats: 75,
            createdAt: new Date().toISOString(),
        },
        // Bangalore to London
        {
            airline: 'British Airways',
            flightNumber: 'BA-119',
            fromLocation: 'Bangalore',
            toLocation: 'London',
            departure: '02:15 AM',
            arrival: '08:30 AM',
            duration: '10h 15m',
            stops: 'Non-stop',
            price: 58000,
            class: 'Economy',
            date: '2024-02-24',
            availableSeats: 160,
            createdAt: new Date().toISOString(),
        },
        {
            airline: 'British Airways',
            flightNumber: 'BA-256',
            fromLocation: 'Delhi',
            toLocation: 'London',
            departure: '09:00 PM',
            arrival: '02:45 AM',
            duration: '9h 45m',
            stops: 'Non-stop',
            price: 135000,
            class: 'Business',
            date: '2024-03-12',
            availableSeats: 55,
            createdAt: new Date().toISOString(),
        },
        // Mumbai to New York
        {
            airline: 'Air India',
            flightNumber: 'AI-191',
            fromLocation: 'Mumbai',
            toLocation: 'New York',
            departure: '01:00 AM',
            arrival: '07:30 AM',
            duration: '14h 30m',
            stops: 'Non-stop',
            price: 65000,
            class: 'Economy',
            date: '2024-03-15',
            availableSeats: 150,
            createdAt: new Date().toISOString(),
        },
        {
            airline: 'Air India',
            flightNumber: 'AI-102',
            fromLocation: 'Delhi',
            toLocation: 'New York',
            departure: '11:30 PM',
            arrival: '08:00 AM',
            duration: '14h 30m',
            stops: '1 Stop',
            price: 52000,
            class: 'Economy',
            date: '2024-03-18',
            availableSeats: 140,
            createdAt: new Date().toISOString(),
        },
        // Bangkok Routes
        {
            airline: 'IndiGo',
            flightNumber: '6E-111',
            fromLocation: 'Delhi',
            toLocation: 'Bangkok',
            departure: '04:30 AM',
            arrival: '10:15 AM',
            duration: '4h 45m',
            stops: 'Non-stop',
            price: 28000,
            class: 'Economy',
            date: '2024-02-26',
            availableSeats: 165,
            createdAt: new Date().toISOString(),
        },
        {
            airline: 'Air India',
            flightNumber: 'AI-333',
            fromLocation: 'Mumbai',
            toLocation: 'Bangkok',
            departure: '12:30 PM',
            arrival: '06:45 PM',
            duration: '5h 15m',
            stops: 'Non-stop',
            price: 32000,
            class: 'Economy',
            date: '2024-03-04',
            availableSeats: 155,
            createdAt: new Date().toISOString(),
        },
        // Paris Route
        {
            airline: 'Lufthansa',
            flightNumber: 'LH-765',
            fromLocation: 'Delhi',
            toLocation: 'Paris',
            departure: '10:45 PM',
            arrival: '05:30 AM',
            duration: '9h 45m',
            stops: '1 Stop',
            price: 48000,
            class: 'Economy',
            date: '2024-03-20',
            availableSeats: 125,
            createdAt: new Date().toISOString(),
        },
        {
            airline: 'Lufthansa',
            flightNumber: 'LH-890',
            fromLocation: 'Mumbai',
            toLocation: 'Paris',
            departure: '08:30 PM',
            arrival: '04:15 AM',
            duration: '10h 45m',
            stops: '1 Stop',
            price: 145000,
            class: 'Business',
            date: '2024-03-25',
            availableSeats: 65,
            createdAt: new Date().toISOString(),
        },
        // Tokyo Route
        {
            airline: 'Air India',
            flightNumber: 'AI-306',
            fromLocation: 'Delhi',
            toLocation: 'Tokyo',
            departure: '11:00 PM',
            arrival: '10:30 AM',
            duration: '8h 30m',
            stops: 'Non-stop',
            price: 55000,
            class: 'Economy',
            date: '2024-03-07',
            availableSeats: 135,
            createdAt: new Date().toISOString(),
        },
        // Sydney Route
        {
            airline: 'Air India',
            flightNumber: 'AI-301',
            fromLocation: 'Delhi',
            toLocation: 'Sydney',
            departure: '01:45 AM',
            arrival: '06:30 PM',
            duration: '13h 45m',
            stops: '1 Stop',
            price: 62000,
            class: 'Economy',
            date: '2024-03-22',
            availableSeats: 120,
            createdAt: new Date().toISOString(),
        },
    ];

    await db.insert(flights).values(sampleFlights);
    
    console.log('✅ Flights seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});