import { db } from '@/db';
import { taxis } from '@/db/schema';

async function main() {
    const sampleTaxis = [
        {
            type: 'Economy',
            model: 'Maruti Swift',
            capacity: 4,
            luggage: 2,
            pricePerKm: 10,
            features: ["AC", "GPS", "Music System", "Sanitized"],
            rating: 4.2,
            totalTrips: 156,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'Economy',
            model: 'Hyundai i10',
            capacity: 4,
            luggage: 2,
            pricePerKm: 11,
            features: ["AC", "GPS", "Phone Charger", "Sanitized"],
            rating: 4.3,
            totalTrips: 203,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'Economy',
            model: 'Tata Tiago',
            capacity: 4,
            luggage: 2,
            pricePerKm: 12,
            features: ["AC", "Music System", "Water Bottles"],
            rating: 4.1,
            totalTrips: 98,
            available: false,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'Sedan',
            model: 'Honda City',
            capacity: 4,
            luggage: 3,
            pricePerKm: 16,
            features: ["AC", "GPS", "WiFi", "Music System", "Phone Charger"],
            rating: 4.6,
            totalTrips: 287,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'Sedan',
            model: 'Hyundai Verna',
            capacity: 4,
            luggage: 3,
            pricePerKm: 15,
            features: ["AC", "GPS", "Music System", "Water Bottles", "Sanitized"],
            rating: 4.5,
            totalTrips: 312,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'Sedan',
            model: 'Toyota Etios',
            capacity: 4,
            luggage: 3,
            pricePerKm: 14,
            features: ["AC", "GPS", "Phone Charger", "Sanitized"],
            rating: 4.4,
            totalTrips: 189,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'Sedan',
            model: 'Maruti Ciaz',
            capacity: 4,
            luggage: 3,
            pricePerKm: 18,
            features: ["AC", "GPS", "WiFi", "Music System", "Water Bottles"],
            rating: 4.7,
            totalTrips: 267,
            available: false,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'SUV',
            model: 'Toyota Innova',
            capacity: 7,
            luggage: 5,
            pricePerKm: 22,
            features: ["AC", "GPS", "WiFi", "Music System", "Child Seat", "Water Bottles"],
            rating: 4.8,
            totalTrips: 432,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'SUV',
            model: 'Mahindra XUV500',
            capacity: 7,
            luggage: 4,
            pricePerKm: 20,
            features: ["AC", "GPS", "Music System", "Phone Charger", "Sanitized"],
            rating: 4.5,
            totalTrips: 234,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'SUV',
            model: 'Tata Safari',
            capacity: 6,
            luggage: 4,
            pricePerKm: 21,
            features: ["AC", "GPS", "WiFi", "Music System", "Child Seat", "Water Bottles"],
            rating: 4.6,
            totalTrips: 198,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'SUV',
            model: 'Kia Seltos',
            capacity: 6,
            luggage: 4,
            pricePerKm: 25,
            features: ["AC", "GPS", "WiFi", "Music System", "Phone Charger", "Sanitized"],
            rating: 4.7,
            totalTrips: 176,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'Luxury',
            model: 'Mercedes E-Class',
            capacity: 4,
            luggage: 3,
            pricePerKm: 60,
            features: ["AC", "GPS", "WiFi", "Music System", "Child Seat", "Phone Charger", "Water Bottles", "Sanitized"],
            rating: 5.0,
            totalTrips: 89,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'Luxury',
            model: 'BMW 5 Series',
            capacity: 4,
            luggage: 3,
            pricePerKm: 55,
            features: ["AC", "GPS", "WiFi", "Music System", "Child Seat", "Phone Charger", "Water Bottles", "Sanitized"],
            rating: 4.9,
            totalTrips: 67,
            available: false,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'Luxury',
            model: 'Audi A6',
            capacity: 4,
            luggage: 3,
            pricePerKm: 50,
            features: ["AC", "GPS", "WiFi", "Music System", "Child Seat", "Phone Charger", "Water Bottles", "Sanitized"],
            rating: 4.9,
            totalTrips: 53,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'Van',
            model: 'Toyota Hiace',
            capacity: 12,
            luggage: 8,
            pricePerKm: 28,
            features: ["AC", "GPS", "Music System", "Phone Charger", "Water Bottles"],
            rating: 4.4,
            totalTrips: 145,
            available: true,
            createdAt: new Date().toISOString(),
        },
        {
            type: 'Van',
            model: 'Force Traveller',
            capacity: 10,
            luggage: 6,
            pricePerKm: 25,
            features: ["AC", "GPS", "Music System", "Sanitized"],
            rating: 4.3,
            totalTrips: 112,
            available: true,
            createdAt: new Date().toISOString(),
        },
    ];

    await db.insert(taxis).values(sampleTaxis);
    
    console.log('✅ Taxis seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});